### ISSUE TITLE
webpack-stream shows error from other instance

### ISSUE THREAD

**Issue by alxbenz** [frontend-framework/build-framework#2]
When starting gulp serve with an intentional error inside a TS-file I see the same error in components and resources TS task. Though they are mapped to different source globs. The watch tasks seems to work fine afterwards.

[15:59:44] Version: webpack 3.8.1
Asset Size Chunks Chunk Names
jquery.plugin.advanced.js 10.9 kB 0 [emitted] jquery.plugin.advanced
Demo.js 6.28 kB 1 [emitted] Demo
jquery.plugin.simple.js 4.21 kB 2 [emitted] jquery.plugin.simple
BoilerplateOptions.js 2.74 kB 3 [emitted] BoilerplateOptions
jquery.plugin.advanced.js.map 12.7 kB 0 [emitted] jquery.plugin.advanced
Demo.js.map 6.48 kB 1 [emitted] Demo
jquery.plugin.simple.js.map 5.27 kB 2 [emitted] jquery.plugin.simple
BoilerplateOptions.js.map 2.47 kB 3 [emitted] BoilerplateOptions

ERROR in /Users/jan.rembold/Github/frontend-framework/app/components/typescript/ts/jquery.plugin.simple.ts
[tsl] ERROR in /Users/jan.rembold/Github/frontend-framework/app/components/typescript/ts/jquery.plugin.simple.ts(16,4)
TS1005: ';' expected.
[15:59:45] Version: webpack 3.8.1
Asset Size Chunks Chunk Names
jquery.plugin.advanced.js 11 kB 0 [emitted] jquery.plugin.advanced
Demo.js 6.28 kB 1 [emitted] Demo
jquery.plugin.simple.js 4.25 kB 2 [emitted] jquery.plugin.simple
BoilerplateOptions.js 2.74 kB 3 [emitted] BoilerplateOptions
jquery.plugin.advanced.js.map 12.8 kB 0 [emitted] jquery.plugin.advanced
Demo.js.map 6.5 kB 1 [emitted] Demo
jquery.plugin.simple.js.map 5.35 kB 2 [emitted] jquery.plugin.simple
BoilerplateOptions.js.map 2.47 kB 3 [emitted] BoilerplateOptions

ERROR in ./app/components/typescript/ts/jquery.plugin.simple.ts
[tsl] ERROR in /Users/jan.rembold/Github/frontend-framework/app/components/typescript/ts/jquery.plugin.simple.ts(16,4)
TS1005: ';' expected.

**Comment by janrembold** [comment]
fixed with https://github.com/frontend-framework/build-framework/commit/6a864b2196ec22a2380c7fb84eea24bc4f46b576
