### ISSUE TITLE
cleanCss rewrites wrong paths 

### ISSUE THREAD

**Issue by janrembold** [frontend-framework/build-framework#25]
I have done a huge rewrite on the build framework to enable lazy loading of node modules. Those changes are currently pushed into this branch: https://github.com/frontend-framework/build-framework/tree/lazy-load-plugins

The only thing I noticed is a faulty path rewrite of the gulp-clean-css plugin. The paths to our generated iconfonts in https://github.com/frontend-framework/frontend-framework/blob/demo-5.x/src/resources/scss/fonts/iconfont/_icons.scss#L1 are rewritten to something like "/dist/resources/css/resources/resources/fonts/icons/Icons.woff" in the build task. It seems that this isn't related to the usage of lazypipes. This seems to be more a result of the whole lazy module rewrite.

I already tried to use gulp-clean-css as before, with direct requires and not as a lazy plugin, with the same faulty result stated above. I think this plugin uses some kind of static storage for base paths and gets confused because we jump between /src, /.tmp and /dist during the build task.

I also removed the gulp-clean-css plugin and added gulp-cssnano. That produced slightly different minified css (seems that line-breaks in legal comments are not removed) but the generated paths are correct.

I don't want to simply change the plugins without any further discussions or getting you oppinions on this topic @timomayer @alxbenz 

What do you think? Or maybe do you see the cause of this bug?

**Comment by janrembold** [comment]
I disabled rebasing of URLs in clean-css task. That fixes the problem with the faulty rewritten paths. 

Do we have some cases where we need rebasing of image urls in SCSS files? I can't think of a situation where I needed that feature. 

But I'm still confused why this didn't happen before?!?!

**Comment by timomayer** [comment]
Maybe because I can not remember a project where we use images in css file? We set them mostly online to be cms editable

**Comment by janrembold** [comment]
In this case it wasn't an image but an icon font path. But in general every url(...) could be affected. But as you said, I also can't remember using an image inside our scss styles in the last few years. ;)

**Comment by janrembold** [comment]
I consider this as resolved
